export const theme = {
  sky: 0x0049fc,
  skyHex: '#0049FC',
  navy: 0x051d2e,
  navyHex: '#051D2E',
  orange: 0xff7420,
  orangeHex: '#FF7420',
  fog: 0xcbe9f2,
  fogHex: '#CBE9F2',
  peach: 0xffbe98,
  peachHex: '#FFBE98',
  khaki: 0xc9b896,
  khakiDark: 0xa89068,
  denim: 0x3d5a80,
  denimDark: 0x2a4060,
  hair: 0xf0cc28,
  hairDark: 0xc49a18,
  skin: 0xe8b896,
  skinShadow: 0xc49272,
  white: 0xf4f7fa,
  asphalt: 0x2b3540,
  concrete: 0x8b93a0,
  brick: 0x4a5d78,
  brickDark: 0x33445c,
  window: 0xffd27a,
  danger: 0xff3b3b,
} as const

export const copy = {
  title: 'TREAD',
  tagline: 'Instala el servicio. Conecta la ciudad.',
  play: 'JUGAR',
  how: 'Junta 8 rollos de coaxial y llega a la última casa.',
  rotate: 'Gira el teléfono para jugar en horizontal',
  cables: 'Cable',
  lives: 'Vidas',
  house: 'Casa',
  installing: 'Instalando servicio…',
  needCable: 'Te falta cable para instalar',
  winTitle: 'Servicio instalado',
  winBody: 'La casa ya tiene señal.',
  failTitle: 'Instalación incompleta',
  failBody: 'El servicio no quedó conectado.',
  again: 'REINTENTAR',
  menu: 'MENÚ',
} as const
